dist: trusty

language: python

python:
    - '2.7'

addons:
  apt:
    packages:
      - pandoc
      - python-h5py
      - python-matplotlib
      - python-scipy
      - python-vtk

before_install:
  - pip install pytest pytest-cov

install:
  - pip install .

script:
  - cd tests && pytest --cov voropy

after_success:
  - bash <(curl -s https://codecov.io/bash)
