version: 2

jobs:
  build:
    working_directory: ~/voropy
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      # don't install sympy with apt: it pulls in texlive which takes for ever
      # to download and install
      - run: apt-get install -y git python3-pip pandoc
      - run: pip3 install -U pytest pytest-cov pylint
      - checkout
      - run: pip3 install -r test_requirements.txt
      - run: pip3 install .
      # lint
      - run: pylint setup.py voropy/ test/*.py
      # make sure that rst converts correctly
      - run: pip3 install docutils pygments
      - run: make README.rst
      # The tests
      - run: cd test/ && MPLBACKEND=Agg pytest --cov voropy
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
