version: 2

jobs:
  doc:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update
      - run: apt install -y python3-pip
      - run: pip3 install -U sphinx
      - run: LC_ALL=C.UTF-8 make doc
  lint:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update
      - run: apt install -y python3-pip
      - run: pip3 install -U black flake8
      - run: LC_ALL=C.UTF-8 black --check setup.py meshplex/ test/*.py
      - run: flake8 setup.py meshplex/ test/*.py
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y git python3-pip
      - run: pip3 install -U pytest pytest-cov excode
      - checkout
      # install
      - run: pip3 install -r test_requirements.txt
      - run: pip3 install .[all]
      # The tests
      - run: excode README.md test/readme_test.py --filter python
      - run: cd test/ && MPLBACKEND=Agg pytest --cov meshplex
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash) -R ~/work

workflows:
  version: 2
  doc_lint_and_build:
    jobs:
      - doc
      - lint
      - build
