version: 2

jobs:
  doc:
    working_directory: ~/work
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip3 install --user sphinx
      - run: make doc
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip3 install --user black flake8
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:19.10
    steps:
      - run: apt-get update
      # <https://stackoverflow.com/a/44333806/353337>
      - run: DEBIAN_FRONTEND=noninteractive apt install tzdata
      - run: apt-get install -y git python3-pip python3-vtk7
      - run: pip3 install -U pytest pytest-cov excode
      - checkout
      # install; need a new pip
      - run: pip3 install pip -U --force
      - run: pip3 install -r test_requirements.txt
      - run: pip3 install .[all]
      # The tests
      - run: excode README.md test/readme_test.py --filter python,test
      - run:
          command: pytest --cov meshplex
          working_directory: test/
          env:
            MPLBACKEND: Agg
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  doc_lint_and_build:
    jobs:
      - doc
      - lint
      - build
